// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/graphzc/sdd-task-management-example/cmd/api/server"
	"github.com/graphzc/sdd-task-management-example/internal/config"
	"github.com/graphzc/sdd-task-management-example/internal/handlers"
	"github.com/graphzc/sdd-task-management-example/internal/handlers/common"
)

// Injectors from wire.go:

func InitializeAPI() *server.EchoServer {
	configConfig := config.NewConfig()
	handler := common.New()
	handlersHandlers := handlers.NewHandlers(handler)
	echoServer := server.NewEchoServer(configConfig, handlersHandlers)
	return echoServer
}
