// Code generated by go-wireset-gen. DO NOT EDIT.

package di

import (
	config "github.com/graphzc/sdd-task-management-example/internal/config"
	handlers "github.com/graphzc/sdd-task-management-example/internal/handlers"
	common "github.com/graphzc/sdd-task-management-example/internal/handlers/common"
	context "github.com/graphzc/sdd-task-management-example/internal/infrastructure/context"
	database "github.com/graphzc/sdd-task-management-example/internal/infrastructure/database"

	"github.com/google/wire"
)

var ConfigSet = wire.NewSet(
	config.NewConfig,
)

var HandlerSet = wire.NewSet(
	handlers.NewHandlers,
	common.New,
)

var InfrastructureSet = wire.NewSet(
	context.NewContext,
	database.NewSQLXClient,
)
